use cagents_core::import::import_agents_md;
use serial_test::serial;
use std::fs;
use tempfile::TempDir;

#[test]
#[serial]
fn test_import_agents_md_recursively() {
    let tmp = TempDir::new().unwrap();
    let _guard = ChangeDir::new(tmp.path());

    // Create nested structure with AGENTS.md files
    fs::create_dir_all("backend").unwrap();
    fs::create_dir_all("frontend").unwrap();

    // Create root-level AGENTS.md
    fs::write(
        "AGENTS.md",
        "# General Rules\n\nAlways write tests."
    ).unwrap();

    // Create nested AGENTS.md files
    fs::write(
        "backend/AGENTS.md",
        "# API Rules\n\nUse REST conventions."
    ).unwrap();

    fs::write(
        "frontend/AGENTS.md",
        "# React Rules\n\nUse functional components."
    ).unwrap();

    // Run import
    import_agents_md(false).unwrap();

    // Verify all templates were created
    assert!(
        std::path::Path::new(".cAGENTS/templates/agents-root.md").exists(),
        "Root level AGENTS.md should be imported as agents-root"
    );

    assert!(
        std::path::Path::new(".cAGENTS/templates/agents-backend.md").exists(),
        "Nested backend AGENTS.md should be imported with directory name"
    );

    assert!(
        std::path::Path::new(".cAGENTS/templates/agents-frontend.md").exists(),
        "Nested frontend AGENTS.md should be imported with directory name"
    );

    // Verify content is preserved
    let root_content = fs::read_to_string(".cAGENTS/templates/agents-root.md").unwrap();
    assert!(root_content.contains("Always write tests"));

    let api_content = fs::read_to_string(".cAGENTS/templates/agents-backend.md").unwrap();
    assert!(api_content.contains("Use REST conventions"));

    let react_content = fs::read_to_string(".cAGENTS/templates/agents-frontend.md").unwrap();
    assert!(react_content.contains("Use functional components"));

    // Verify nested files were removed (root AGENTS.md gets regenerated by build)
    assert!(!std::path::Path::new("backend/AGENTS.md").exists(), "Nested backend AGENTS.md should be removed");
    assert!(!std::path::Path::new("frontend/AGENTS.md").exists(), "Nested frontend AGENTS.md should be removed");

    // Root AGENTS.md will exist because build regenerates it
    assert!(std::path::Path::new("AGENTS.md").exists(), "Root AGENTS.md should be regenerated by build");
}

/// Helper to change directory and restore on drop
struct ChangeDir {
    original: std::path::PathBuf,
}

impl ChangeDir {
    fn new(path: &std::path::Path) -> Self {
        let original = std::env::current_dir().unwrap();
        std::env::set_current_dir(path).unwrap();
        Self { original }
    }
}

impl Drop for ChangeDir {
    fn drop(&mut self) {
        let _ = std::env::set_current_dir(&self.original);
    }
}
