name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      # Cache pnpm dependencies
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm -w i

      - name: Setup Rust (needed for version sync)
        uses: dtolnay/rust-toolchain@stable

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          # This runs "pnpm run version" which calls changeset version + sync-versions.js
          version: pnpm run version
          # This runs "pnpm run release" which builds and publishes to npm
          publish: pnpm run release
          title: "Release: Version Packages"
          commit: "chore: version packages"
          setupGitUser: true
          createGithubReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_DEPLOY_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Setup Rust
        if: steps.changesets.outputs.published == 'true'
        uses: dtolnay/rust-toolchain@stable

      # Cache Rust dependencies for faster builds
      - uses: Swatinem/rust-cache@v2
        if: steps.changesets.outputs.published == 'true'
        with:
          cache-on-failure: true

      - name: Publish to crates.io
        if: steps.changesets.outputs.published == 'true'
        run: |
          cargo login ${{ secrets.CARGO_REGISTRY_TOKEN }}
          # Publish core first (cli depends on it)
          cd crates/cagents-core
          cargo publish --allow-dirty
          cd ../cagents-cli
          # Wait for crates.io to index the core crate
          sleep 30
          cargo publish --allow-dirty
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Create GitHub Release
        if: steps.changesets.outputs.published == 'true'
        run: |
          # Extract version from published packages
          VERSION=$(cat packages/cagents/package.json | jq -r '.version')
          gh release create "v${VERSION}" \
            --title "v${VERSION}" \
            --notes "See [CHANGELOG.md](./CHANGELOG.md) for details."
        env:
          GITHUB_TOKEN: ${{ secrets.GH_DEPLOY_TOKEN }}
